#!/bin/bash
# GuardGuote - Cloudflare Tunnel Setup for Pi1
# "The typo that became a brand"
#
# Run this script on Pi1 (192.168.2.70)
# Usage: ./setup-pi1.sh

set -e

echo "🚇 GuardGuote Cloudflare Tunnel Setup"
echo "======================================"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if running on Pi1
HOSTNAME=$(hostname)
if [[ "$HOSTNAME" != *"pi"* ]] && [[ "$HOSTNAME" != *"raspberry"* ]]; then
    echo -e "${YELLOW}Warning: This doesn't look like a Raspberry Pi. Continue anyway? (y/n)${NC}"
    read -r confirm
    if [[ "$confirm" != "y" ]]; then
        exit 1
    fi
fi

# Step 1: Install cloudflared
echo -e "${GREEN}[1/7] Installing cloudflared...${NC}"
if command -v cloudflared &> /dev/null; then
    echo "cloudflared already installed: $(cloudflared --version)"
else
    # Detect architecture
    ARCH=$(uname -m)
    if [[ "$ARCH" == "aarch64" ]] || [[ "$ARCH" == "arm64" ]]; then
        CLOUDFLARED_URL="https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64"
    elif [[ "$ARCH" == "armv7l" ]]; then
        CLOUDFLARED_URL="https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm"
    else
        CLOUDFLARED_URL="https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64"
    fi

    echo "Downloading from: $CLOUDFLARED_URL"
    curl -L "$CLOUDFLARED_URL" -o cloudflared
    chmod +x cloudflared
    sudo mv cloudflared /usr/local/bin/
    echo "Installed: $(cloudflared --version)"
fi

# Step 2: Authenticate with Cloudflare
echo ""
echo -e "${GREEN}[2/7] Authenticating with Cloudflare...${NC}"
if [[ -f ~/.cloudflared/cert.pem ]]; then
    echo "Already authenticated (cert.pem exists)"
else
    echo "Opening browser for authentication..."
    echo "If no browser opens, visit the URL shown below:"
    cloudflared tunnel login
fi

# Step 3: Create tunnel
echo ""
echo -e "${GREEN}[3/7] Creating tunnel...${NC}"
TUNNEL_NAME="guardguote-pi1"

if cloudflared tunnel list | grep -q "$TUNNEL_NAME"; then
    echo "Tunnel '$TUNNEL_NAME' already exists"
    TUNNEL_ID=$(cloudflared tunnel list | grep "$TUNNEL_NAME" | awk '{print $1}')
else
    cloudflared tunnel create "$TUNNEL_NAME"
    TUNNEL_ID=$(cloudflared tunnel list | grep "$TUNNEL_NAME" | awk '{print $1}')
fi
echo "Tunnel ID: $TUNNEL_ID"

# Step 4: Create config file
echo ""
echo -e "${GREEN}[4/7] Creating config file...${NC}"
mkdir -p ~/.cloudflared

cat > ~/.cloudflared/config.yml << EOF
# GuardGuote Cloudflare Tunnel - Pi1
# Auto-generated by setup-pi1.sh

tunnel: $TUNNEL_ID
credentials-file: /home/$USER/.cloudflared/$TUNNEL_ID.json

ingress:
  # Backend API (Bun + Hono)
  - hostname: pi1.guardguote.com
    service: http://localhost:3000
    originRequest:
      noTLSVerify: true
      connectTimeout: 30s

  # ML Engine (FastAPI)
  - hostname: ml-pi1.guardguote.com
    service: http://localhost:8000
    originRequest:
      noTLSVerify: true
      connectTimeout: 60s

  # Health check
  - hostname: health-pi1.guardguote.com
    service: http://localhost:3000/health

  # Catch-all
  - service: http_status:404
EOF

echo "Config written to ~/.cloudflared/config.yml"

# Step 5: Route DNS
echo ""
echo -e "${GREEN}[5/7] Setting up DNS routes...${NC}"
echo "Routing pi1.guardguote.com..."
cloudflared tunnel route dns "$TUNNEL_NAME" pi1.guardguote.com || echo "Route may already exist"

echo "Routing ml-pi1.guardguote.com..."
cloudflared tunnel route dns "$TUNNEL_NAME" ml-pi1.guardguote.com || echo "Route may already exist"

echo "Routing health-pi1.guardguote.com..."
cloudflared tunnel route dns "$TUNNEL_NAME" health-pi1.guardguote.com || echo "Route may already exist"

# Step 6: Test tunnel
echo ""
echo -e "${GREEN}[6/7] Testing tunnel...${NC}"
echo "Starting tunnel in foreground for 5 seconds..."
timeout 5 cloudflared tunnel run "$TUNNEL_NAME" &
sleep 3
kill %1 2>/dev/null || true
echo "Tunnel test complete"

# Step 7: Install as service
echo ""
echo -e "${GREEN}[7/7] Installing as system service...${NC}"
echo "This requires sudo privileges..."

sudo cloudflared service install || echo "Service may already be installed"
sudo systemctl enable cloudflared
sudo systemctl start cloudflared

echo ""
echo "======================================"
echo -e "${GREEN}✅ Setup Complete!${NC}"
echo "======================================"
echo ""
echo "Tunnel ID: $TUNNEL_ID"
echo "Hostnames:"
echo "  - https://pi1.guardguote.com (Backend API)"
echo "  - https://ml-pi1.guardguote.com (ML Engine)"
echo "  - https://health-pi1.guardguote.com (Health Check)"
echo ""
echo "Service status:"
sudo systemctl status cloudflared --no-pager | head -10
echo ""
echo "Test with:"
echo "  curl https://health-pi1.guardguote.com"
echo ""
echo "Logs:"
echo "  sudo journalctl -u cloudflared -f"
