# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ml_engine_pb2 as ml__engine__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ml_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QuoteServiceStub(object):
    """============================================================================
    Quote Service
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateQuote = channel.unary_unary(
                '/guardquote.ml.QuoteService/GenerateQuote',
                request_serializer=ml__engine__pb2.QuoteRequest.SerializeToString,
                response_deserializer=ml__engine__pb2.QuoteResponse.FromString,
                _registered_method=True)
        self.GenerateQuoteRuleBased = channel.unary_unary(
                '/guardquote.ml.QuoteService/GenerateQuoteRuleBased',
                request_serializer=ml__engine__pb2.QuoteRequest.SerializeToString,
                response_deserializer=ml__engine__pb2.QuoteResponse.FromString,
                _registered_method=True)
        self.GenerateQuotesBatch = channel.stream_stream(
                '/guardquote.ml.QuoteService/GenerateQuotesBatch',
                request_serializer=ml__engine__pb2.QuoteRequest.SerializeToString,
                response_deserializer=ml__engine__pb2.QuoteResponse.FromString,
                _registered_method=True)


class QuoteServiceServicer(object):
    """============================================================================
    Quote Service
    ============================================================================

    """

    def GenerateQuote(self, request, context):
        """Generate a price quote using trained ML model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateQuoteRuleBased(self, request, context):
        """Generate a price quote using rule-based engine (fallback)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateQuotesBatch(self, request_iterator, context):
        """Streaming batch quotes for bulk pricing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuoteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateQuote': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateQuote,
                    request_deserializer=ml__engine__pb2.QuoteRequest.FromString,
                    response_serializer=ml__engine__pb2.QuoteResponse.SerializeToString,
            ),
            'GenerateQuoteRuleBased': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateQuoteRuleBased,
                    request_deserializer=ml__engine__pb2.QuoteRequest.FromString,
                    response_serializer=ml__engine__pb2.QuoteResponse.SerializeToString,
            ),
            'GenerateQuotesBatch': grpc.stream_stream_rpc_method_handler(
                    servicer.GenerateQuotesBatch,
                    request_deserializer=ml__engine__pb2.QuoteRequest.FromString,
                    response_serializer=ml__engine__pb2.QuoteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'guardquote.ml.QuoteService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('guardquote.ml.QuoteService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QuoteService(object):
    """============================================================================
    Quote Service
    ============================================================================

    """

    @staticmethod
    def GenerateQuote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/guardquote.ml.QuoteService/GenerateQuote',
            ml__engine__pb2.QuoteRequest.SerializeToString,
            ml__engine__pb2.QuoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateQuoteRuleBased(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/guardquote.ml.QuoteService/GenerateQuoteRuleBased',
            ml__engine__pb2.QuoteRequest.SerializeToString,
            ml__engine__pb2.QuoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateQuotesBatch(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/guardquote.ml.QuoteService/GenerateQuotesBatch',
            ml__engine__pb2.QuoteRequest.SerializeToString,
            ml__engine__pb2.QuoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RiskServiceStub(object):
    """============================================================================
    Risk Assessment Service
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AssessRisk = channel.unary_unary(
                '/guardquote.ml.RiskService/AssessRisk',
                request_serializer=ml__engine__pb2.RiskRequest.SerializeToString,
                response_deserializer=ml__engine__pb2.RiskResponse.FromString,
                _registered_method=True)
        self.AssessRiskBatch = channel.stream_stream(
                '/guardquote.ml.RiskService/AssessRiskBatch',
                request_serializer=ml__engine__pb2.RiskRequest.SerializeToString,
                response_deserializer=ml__engine__pb2.RiskResponse.FromString,
                _registered_method=True)


class RiskServiceServicer(object):
    """============================================================================
    Risk Assessment Service
    ============================================================================

    """

    def AssessRisk(self, request, context):
        """Get detailed risk assessment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssessRiskBatch(self, request_iterator, context):
        """Streaming risk assessments for batch processing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RiskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AssessRisk': grpc.unary_unary_rpc_method_handler(
                    servicer.AssessRisk,
                    request_deserializer=ml__engine__pb2.RiskRequest.FromString,
                    response_serializer=ml__engine__pb2.RiskResponse.SerializeToString,
            ),
            'AssessRiskBatch': grpc.stream_stream_rpc_method_handler(
                    servicer.AssessRiskBatch,
                    request_deserializer=ml__engine__pb2.RiskRequest.FromString,
                    response_serializer=ml__engine__pb2.RiskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'guardquote.ml.RiskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('guardquote.ml.RiskService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RiskService(object):
    """============================================================================
    Risk Assessment Service
    ============================================================================

    """

    @staticmethod
    def AssessRisk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/guardquote.ml.RiskService/AssessRisk',
            ml__engine__pb2.RiskRequest.SerializeToString,
            ml__engine__pb2.RiskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssessRiskBatch(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/guardquote.ml.RiskService/AssessRiskBatch',
            ml__engine__pb2.RiskRequest.SerializeToString,
            ml__engine__pb2.RiskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ModelServiceStub(object):
    """============================================================================
    Model Info Service
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/guardquote.ml.ModelService/HealthCheck',
                request_serializer=ml__engine__pb2.HealthRequest.SerializeToString,
                response_deserializer=ml__engine__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/guardquote.ml.ModelService/GetModelInfo',
                request_serializer=ml__engine__pb2.ModelInfoRequest.SerializeToString,
                response_deserializer=ml__engine__pb2.ModelInfoResponse.FromString,
                _registered_method=True)
        self.GetEventTypes = channel.unary_unary(
                '/guardquote.ml.ModelService/GetEventTypes',
                request_serializer=ml__engine__pb2.EventTypesRequest.SerializeToString,
                response_deserializer=ml__engine__pb2.EventTypesResponse.FromString,
                _registered_method=True)


class ModelServiceServicer(object):
    """============================================================================
    Model Info Service
    ============================================================================

    """

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """Get model information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEventTypes(self, request, context):
        """Get available event types
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=ml__engine__pb2.HealthRequest.FromString,
                    response_serializer=ml__engine__pb2.HealthResponse.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=ml__engine__pb2.ModelInfoRequest.FromString,
                    response_serializer=ml__engine__pb2.ModelInfoResponse.SerializeToString,
            ),
            'GetEventTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEventTypes,
                    request_deserializer=ml__engine__pb2.EventTypesRequest.FromString,
                    response_serializer=ml__engine__pb2.EventTypesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'guardquote.ml.ModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('guardquote.ml.ModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelService(object):
    """============================================================================
    Model Info Service
    ============================================================================

    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/guardquote.ml.ModelService/HealthCheck',
            ml__engine__pb2.HealthRequest.SerializeToString,
            ml__engine__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/guardquote.ml.ModelService/GetModelInfo',
            ml__engine__pb2.ModelInfoRequest.SerializeToString,
            ml__engine__pb2.ModelInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEventTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/guardquote.ml.ModelService/GetEventTypes',
            ml__engine__pb2.EventTypesRequest.SerializeToString,
            ml__engine__pb2.EventTypesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
