AWSTemplateFormatVersion: '2010-09-09'
Description: 'GuardQuote Secrets Manager - Centralized secrets and credentials management'

Parameters:
  EnvironmentName:
    Description: Environment name (dev, staging, prod)
    Type: String
    Default: dev

  DatabasePassword:
    Description: Database password (will be stored in Secrets Manager)
    Type: String
    NoEcho: true
    Default: ''

  RedisPassword:
    Description: Redis password (will be stored in Secrets Manager)
    Type: String
    NoEcho: true
    Default: ''

  JWTSecret:
    Description: JWT signing secret
    Type: String
    NoEcho: true
    Default: ''

  APIKey:
    Description: External API key
    Type: String
    NoEcho: true
    Default: ''

  EnableAutoRotation:
    Description: Enable automatic secret rotation
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']

  RotationDays:
    Description: Number of days between automatic rotations
    Type: Number
    Default: 30
    MinValue: 1
    MaxValue: 365

Conditions:
  HasDBPassword: !Not [!Equals [!Ref DatabasePassword, '']]
  HasRedisPassword: !Not [!Equals [!Ref RedisPassword, '']]
  HasJWTSecret: !Not [!Equals [!Ref JWTSecret, '']]
  HasAPIKey: !Not [!Equals [!Ref APIKey, '']]
  EnableRotation: !Equals [!Ref EnableAutoRotation, 'true']

Resources:
  # KMS Key for secrets encryption
  SecretsKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub KMS key for ${EnvironmentName} Secrets Manager encryption
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'
          - Sid: Allow Secrets Manager
            Effect: Allow
            Principal:
              Service: secretsmanager.amazonaws.com
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-secrets-kms-key

  SecretsKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${EnvironmentName}-guardquote-secrets
      TargetKeyId: !Ref SecretsKMSKey

  # Application Secrets (combined)
  ApplicationSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${EnvironmentName}/guardquote/application
      Description: !Sub GuardQuote application secrets for ${EnvironmentName}
      KmsKeyId: !Ref SecretsKMSKey
      SecretString: !Sub |
        {
          "NODE_ENV": "${EnvironmentName}",
          "DATABASE_URL": "postgresql://guardquote:${DatabasePassword}@placeholder:5432/guardquote",
          "REDIS_URL": "redis://:${RedisPassword}@placeholder:6379",
          "JWT_SECRET": "${JWTSecret}",
          "API_KEY": "${APIKey}",
          "LOG_LEVEL": "info"
        }
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-application-secrets
        - Key: Environment
          Value: !Ref EnvironmentName

  # Database Credentials
  DatabaseCredentials:
    Type: AWS::SecretsManager::Secret
    Condition: HasDBPassword
    Properties:
      Name: !Sub ${EnvironmentName}/guardquote/database/credentials
      Description: !Sub Database credentials for ${EnvironmentName}
      KmsKeyId: !Ref SecretsKMSKey
      SecretString: !Sub |
        {
          "engine": "postgres",
          "host": "placeholder.rds.amazonaws.com",
          "port": 5432,
          "username": "guardquote_admin",
          "password": "${DatabasePassword}",
          "dbname": "guardquote"
        }
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-database-credentials
        - Key: Environment
          Value: !Ref EnvironmentName

  # Redis Credentials
  RedisCredentials:
    Type: AWS::SecretsManager::Secret
    Condition: HasRedisPassword
    Properties:
      Name: !Sub ${EnvironmentName}/guardquote/redis/credentials
      Description: !Sub Redis credentials for ${EnvironmentName}
      KmsKeyId: !Ref SecretsKMSKey
      SecretString: !Sub |
        {
          "host": "placeholder.cache.amazonaws.com",
          "port": 6379,
          "authToken": "${RedisPassword}",
          "ssl": true
        }
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-redis-credentials
        - Key: Environment
          Value: !Ref EnvironmentName

  # API Keys and Tokens
  APIKeysSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${EnvironmentName}/guardquote/api-keys
      Description: !Sub API keys and tokens for ${EnvironmentName}
      KmsKeyId: !Ref SecretsKMSKey
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"environment": "${EnvironmentName}"}'
        GenerateStringKey: internal_api_key
        PasswordLength: 64
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-api-keys
        - Key: Environment
          Value: !Ref EnvironmentName

  # ML Model Credentials (for external ML services)
  MLCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${EnvironmentName}/guardquote/ml-credentials
      Description: !Sub ML service credentials for ${EnvironmentName}
      KmsKeyId: !Ref SecretsKMSKey
      SecretString: |
        {
          "sagemaker_endpoint": "placeholder",
          "openai_api_key": "placeholder",
          "anthropic_api_key": "placeholder",
          "huggingface_token": "placeholder"
        }
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-ml-credentials
        - Key: Environment
          Value: !Ref EnvironmentName

  # OAuth Credentials
  OAuthCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${EnvironmentName}/guardquote/oauth
      Description: !Sub OAuth provider credentials for ${EnvironmentName}
      KmsKeyId: !Ref SecretsKMSKey
      SecretString: |
        {
          "google": {
            "client_id": "placeholder",
            "client_secret": "placeholder"
          },
          "microsoft": {
            "client_id": "placeholder",
            "client_secret": "placeholder",
            "tenant_id": "placeholder"
          },
          "github": {
            "client_id": "placeholder",
            "client_secret": "placeholder"
          }
        }
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-oauth-credentials
        - Key: Environment
          Value: !Ref EnvironmentName

  # IAM Policy for reading secrets
  SecretsReadPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub ${EnvironmentName}-guardquote-secrets-read
      Description: Policy to read GuardQuote secrets
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: GetSecrets
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Resource:
              - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${EnvironmentName}/guardquote/*
          - Sid: DecryptSecrets
            Effect: Allow
            Action:
              - kms:Decrypt
              - kms:DescribeKey
            Resource: !GetAtt SecretsKMSKey.Arn

  # Resource Policy for cross-account access (if needed)
  SecretsResourcePolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref ApplicationSecrets
      ResourcePolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowAccountAccess
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Resource: '*'

Outputs:
  ApplicationSecretsArn:
    Description: Application Secrets ARN
    Value: !Ref ApplicationSecrets
    Export:
      Name: !Sub ${EnvironmentName}-ApplicationSecretsArn

  DatabaseCredentialsArn:
    Condition: HasDBPassword
    Description: Database Credentials Secret ARN
    Value: !Ref DatabaseCredentials
    Export:
      Name: !Sub ${EnvironmentName}-DatabaseCredentialsArn

  RedisCredentialsArn:
    Condition: HasRedisPassword
    Description: Redis Credentials Secret ARN
    Value: !Ref RedisCredentials
    Export:
      Name: !Sub ${EnvironmentName}-RedisCredentialsArn

  APIKeysSecretArn:
    Description: API Keys Secret ARN
    Value: !Ref APIKeysSecret
    Export:
      Name: !Sub ${EnvironmentName}-APIKeysSecretArn

  MLCredentialsArn:
    Description: ML Credentials Secret ARN
    Value: !Ref MLCredentials
    Export:
      Name: !Sub ${EnvironmentName}-MLCredentialsArn

  OAuthCredentialsArn:
    Description: OAuth Credentials Secret ARN
    Value: !Ref OAuthCredentials
    Export:
      Name: !Sub ${EnvironmentName}-OAuthCredentialsArn

  SecretsKMSKeyArn:
    Description: Secrets KMS Key ARN
    Value: !GetAtt SecretsKMSKey.Arn
    Export:
      Name: !Sub ${EnvironmentName}-SecretsKMSKeyArn

  SecretsReadPolicyArn:
    Description: IAM Policy ARN for reading secrets
    Value: !Ref SecretsReadPolicy
    Export:
      Name: !Sub ${EnvironmentName}-SecretsReadPolicyArn
